name: Validate

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  hacs:
    runs-on: ubuntu-latest
    name: HACS
    steps:
      - uses: actions/checkout@v5
      - uses: hacs/action@main
        with:
          category: integration

  hassfest:
    runs-on: ubuntu-latest
    name: Hassfest
    steps:
      - uses: actions/checkout@v5
      - uses: home-assistant/actions/hassfest@master
